<?php

// Output the REDCap icon with the specified colour.


namespace Nottingham\REDCapUITweaker;


// Return 404 status if invalid colour specified.
if ( ! preg_match( '/^[0-9a-f]{6}$/', $_GET['c'] ) )
{
	header( 'HTTP/1.1 404 Not Found' );
	exit;
}

// Define icon image.
$icon = <<<'ICON_DATA'
AAABAAQAMDAAAAEAIACoJQAARgAAACAgAAABACAAqBAAAO4lAAAYGAAAAQAgAIgJAACWNgAAEBAAAAEAIABoBAAAHkAAACgAAAAw
AAAAYAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzZ7RTs9O0U7PTtFOz07RTs9O0U7PTtFOz07RTs
UgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsG+0U7PHtFOz07RTs9O0U7PTtFOz07RTs9O0U7PTtFOx0AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAADtFOzz7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
7RTsou0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7PrtFOwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzV7RTs/+0U7P/tFOz/7RTs/+0U
7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwG7RTs9u0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7IsA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAADtFOzQ7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADtFOxr7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs8u0U7AYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOy77RTs/+0U7P/t
FOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzl7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/
7RTseQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOyZ7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAO0U7EXtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOzp7RTsAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOyZ
7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7NDtFOz/7RTs/+0U7P/tFOz/7RTs
/+0U7P/tFOxVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOxw7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAA
AAAAAAAAAAAAAAAAAAAA7RTsIe0U7P7tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADtFOxL7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTskgAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsxe0U7P/tFOz/7RTs/+0U
7P/tFOz/7RTs/+0U7DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOxL7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/
7RTsowAAAAAAAAAAAAAAAAAAAADtFOwl7RTs/u0U7P/tFOz/7RTs/+0U7P/tFOz/7RTszgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADtFOw37RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAAAAAADtFOzB7RTs/+0U7P/t
FOz/7RTs/+0U7P/tFOz97RTsIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTs/+0U7P/tFOz/7RTs
/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAO0U7B/tFOz97RTs/+0U7P/tFOz/7RTs/+0U7P/tFOy4AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAO0U7LTtFOz/
7RTs/+0U7P/tFOz/7RTs/+0U7PztFOwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqmMC8qp+ovKqfeLyqm
SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTs/+0U
7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAA7RTsFu0U7PztFOz/7RTs/+0U7P/tFOz/7RTs/+0U7JkAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnxC8qp/8vKqf/Lyqn/i8qp10AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyKLYj
Mym2hDMpts0yKLftMii18zIotvMyKLfuMii3zjIot38wJ7cO7RTs++0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsrwAAAAAAAAAA7RTs
re0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7OztFOyu7RTsOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnoi8q
p/8vKqf/Lyqn/y8qp/svKqYXAAAAAAAAAAAyKLZLMym2sTMpte4yKbT/Mym2/zIps/8zKbb/Mym2/zMptv8yKLb/MSi0/zIot/8y
KLb8IRp+/u0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsxwAAAADtFOwS7RTs/O0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/
7RTs/+0U7OrtFOxhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALymqEC8qqfYvKqf/Lyqn/y8qp/8wKa29Mym2vTMptvgzKbX/Mim0
/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLX/Mii2/ywkoP/tFOz/7RTs/+0U7P/tFOz/7RTs3AAA
AADtFOyp7RTs/+0U7PztFOz87RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsxO0U7AQAAAAAAAAAAAAAAAAA
AAAAAAAAADIps1kyKbL/Mimy/zIps/8zKbX/Mym1/zMptf8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/
Mym2/zMptv8zKbb/Mii3/zEotP8vJqz/7RTs/+0U7P/tFOz/7RTs3QAAAADtFOwj7RTsIwAAAAAAAAAA7RTsHe0U7F3tFOzD7RTs
/u0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7M4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzKbbBMym2/zMptv8zKbb/Mym2/zMp
tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLb/Liak/+0U7P/t
FOz/7RTs3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsKO0U7PHtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOx/
AAAAAAAAAAAAAAAAAAAAAAAAAAAzKbYMMym29TMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2
/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLf/Mii1/yghj//tFOz/7RTs3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAO0U7BvtFOz67RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMym2VzMptv8z
Kbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/
Mii3/zIotf8cFmf/7RTs3wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOyx7RTs/+0U7P/tFOz/7RTs
/+0U7P/tFOz/7RTsPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMptsAzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp
tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii3/zIotf8xKLH/7RTs5QAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOxr7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTskwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADMptgozKbb1Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2
/zMptv8zKbb/Mii3/zIot/8yKLX/MCep+TIotwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOxk7RTs/+0U
7P/tFOz/7RTs/+0U7P/tFOz/7RTsvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyKbZVMym2/zMptv8zKbb/Mym2/zMptv8z
Kbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLf/Mii2/zIot5wAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOx97RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsyQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAMym2vDMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp
tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMotv8yKLf/Mii2/zIotv0xJ7cmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ALt
FOzh7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCiuKjIps/8zKbb/
Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii3
/zIotf8xKLfOAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwG7RTsS+0U7NztFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsXwAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp/8wKqv/MSmv/zIpsv8yKbP/Mimz/zIps/8yKbP/Mimz/zIpsf8x
KbD/MSqu/zEqrf8xKq3/MSqt/zEpsP8xKbH/Mimz/zMptf8zKbb/Mii3/zIot/8yKLX/7RTs3e0U7NztFOzc7RTs3O0U7OrtFOz7
7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz57RTsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AC8qp/wvKqf/Lyqn/y8qqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q
p/8wKqn/MCmu/zAqrv8xKbH/JR2N/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/t
FOx6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp/4vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/
Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8rpv8uLqH/Li2h/x8fbv/tFOz/7RTs
/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7KEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAALiipCi8qp/8vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8vK6b/Li2i/y4uof8rK5f/ISFt/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz3
7RTsdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqnTS8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn
/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8qp/8vKqf/Lyqm/y4t
o/8uLqH/Li6h/y0tnv8qKoj/Hx9r/+0U7P/tFOzq7RTswu0U7GLtFOwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAALiqniC8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/
Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqp/y8qp/8vKqf/Lyqn/y8qp/8uLKT/Li6h/y4uof8uLqH/Li6h/y4uof8uLqHwAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnoi8qp/8vKqf/Lyqn/y8q
qf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/Li2i/y4uof8uLqH/Li6h/y4uof8uLqHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqnzC8qp/8vKqf/Lyqn/y8qqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn
/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyum/y4uof8uLqH/Li6h/y4u
of85OqadAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnzy8qp/8v
Kqf/Lyqn/zAqqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqn/
Lyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4tov8uLqH/Li6h/zAwof9OT6szAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnoi8qp/8vKqf/Lyqn/y8qqP8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8q
p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4spP8u
LqH/Li6h/zIyovYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
LimnYi8qp/8vKqf/Lyqn/y8qp/8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn
/y8qp/8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8spf8uLqH/Li6h/zAworoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALymqBC8qp/kvKqf/Lyqn/y8qp/8wKqr/Lyqn/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/
Lyqn/y8spP8uLqH/Li6h/y4voksAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAC8qp6MvKqf/Lyqn/y8qp/8vKqj/Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q
p/8vKqf/Lyqn/y8qqP8vKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4so/8uLqH/Li6h8AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8rpwwvKqf3Lyql/y8qp/8vKqf/
Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn
/y8qp/8vKqf/Lyqn/y4uov8uLqH/Li6ijwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaZfLyqk/y8qp/8vKqf/Lyqn/zAqqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyul/y4uof8uLqH6Li2jDAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqn
ki8qp/8vKqf/Lyqn/y8qqf8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8qpf8vKqb/Lyqn/y8qp/8vKqf/Lyqo/y8qqP8vKqf/Lyqn/y8q
p/8vKqf/Lyqn/y8qp/8vKqf/Li2i/y4uof8uLqGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp5QvKqf/Lyqn/y8qp/8wKqr/Lyqn/y8qp/8vKqf/
Lyqn/y8qpP8vKqX/Lyqn/y8qp/8vKqf/Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vLKT/Li6h/y4uoewtKaMGAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAvKqZlLyqn+S8qp/8vKqf/MCqq/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqp/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/Lyqm/y8rpf8uLqH/Li6h/S0toi4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALimnEC4qpq8vKqf7Lyqn
/zAqqv8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8qqP8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqX/Liui/y4uof8uLaH9Li2hUgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqcMLyqneS8qp9gwKqr6Lyqp/y8qp/8vKqf/Lyqo/zAqqv8vKqf/
Lyqn/y8qp/8vKqf/Lyqn/y8qp/8uLKT/Li6h/y4touwuK6Q3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAALymldC4po/8vKaT/Lyqp6C8qp/EvKqf9Lyqn/y8qp/8wK6b/PDup+C4tousuLqHDLiyiZAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0pnyouKZ8/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///gP/AcAAP//+A/4BwAA///4D/gHAAD///gP+A8AAP//+A/wHwAA///4D/AfAAD/
//gP4D8AAP///A/gPwAA///8B8B/AAD///wHwH8AAP///AeA/wAA///8B4D/AAD///wHAf8AAM///AcB/wAAh/gMBgD/AACDwAAG
AD8AAMAAAAQADwAA4AAAB/AHAADgAAAH/AcAAPAAAAf+AwAA+AAAB/4DAAD4AAAH/wEAAPwAAAf/AQAA/gAAA/8BAAD+AAAD/gEA
AP8AAAH8AwAA/wAAAAADAAD/AAAAAAcAAP8AAAAABwAA/wAAAAAfAAD/AAAAAH8AAP4AAAAA/wAA/gAAAAD/AAD+AAAAAP8AAP4A
AAAB/wAA/gAAAAH/AAD/AAAAAf8AAP8AAAAD/wAA/wAAAAP/AAD/gAAAA/8AAP/AAAAH/wAA/8AAAAf/AAD/4AAAD/8AAP/4AAAf
/wAA//wAAD//AAD//4AAf/8AAP//8AH//wAA////////AAAoAAAAIAAAAEAAAAABACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7BDtFOzZ7RTs9+0U7PftFOz37RTs
xe0U7BwAAAAAAAAAAAAAAAAAAAAA7RTsF+0U7L7tFOz37RTs9+0U7PftFOzr7RTsRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsEO0U7NntFOz/7RTs/+0U7P/tFOzO7RTsIQAAAAAAAAAAAAAAAO0U7AHt
FOxN7RTs8+0U7P/tFOz/7RTs/u0U7LbtFOwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADtFOwO7RTszO0U7P/tFOz/7RTs/+0U7M7tFOwhAAAAAAAAAAAAAAAA7RTsCu0U7KbtFOz/7RTs/+0U7P/tFOzu7RTs
Se0U7AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7AztFOy17RTs/+0U
7P/tFOz/7RTszu0U7CEAAAAAAAAAAAAAAADtFOw07RTs7O0U7P/tFOz/7RTs/e0U7KvtFOwNAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsCu0U7KftFOz/7RTs/+0U7P/tFOzO7RTsIQAAAAAAAAAA
7RTsBO0U7JftFOz87RTs/+0U7P/tFOzs7RTsOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAADtFOwG7RTshu0U7P/tFOz/7RTs/+0U7NjtFOwrAAAAAAAAAADtFOwx7RTs3e0U7P/tFOz/7RTs/e0U
7I3tFOwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7AXt
FOx77RTs/+0U7P/tFOz/7RTs4u0U7DUAAAAA7RTsBu0U7IPtFOz97RTs/+0U7P/tFOze7RTsMwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsAe0U7FztFOz+7RTs/+0U7P/tFOzk7RTs
NwAAAADtFOwk7RTs4u0U7P/tFOz/7RTs++0U7IztFOwEAAAAAAAAAAAAAAAAAAAAAC8qpgUvKqc3LyqnOC8qpggAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAyKLYBMii2ATIotwEAAAAA7RTsUe0U7P7tFOz/7RTs/+0U7OTtFOw37RTsA+0U7IrtFOz77RTs/+0U7P/t
FOza7RTsHwAAAAAAAAAAAAAAAAAAAAAAAAAALyqnLy8qp9cvKqflLyqnbC8qpwYAAAAAMym2BzMptREzKbY5Mym2gjIotqMyKLan
Mii3njIot2rtFOxn7RTs/u0U7P/tFOz/7RTs5e0U7DjtFOwq7RTs1u0U7P/tFOz/7RTs/+0U7NvtFOxs7RTsG+0U7AUAAAAAAAAA
AAAAAAAvKqcmLyqn0S8qp/8vKqfqMCmtUjMptkwzKbWQMym12DMptfEzKbX6Mym2/jMptv4yKLb9Mii29y4lqvMcFm//7RTs/+0U
7P/tFOzu7RTsRe0U7HbtFOz77RTs/u0U7P7tFOz/7RTs/u0U7PftFOzg7RTsee0U7BUAAAAAAAAAAC8pqgIwKq1kMSmv9DEpsP0y
KbTrMym19jMptv4zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/zAnr/8jHIX/7RTs/+0U7PTtFOxL7RTsTu0U7FftFOxW
7RTsgu0U7NDtFOz57RTs/+0U7P/tFOz47RTspO0U7BAAAAAAAAAAADMptQ4zKbamMym2/jMptv8zKbb/Mym2/zMptv8zKbb/Mym2
/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/zEnsf8fGXb/7RTs9O0U7EftFOwC7RTsAe0U7AHtFOwG7RTsF+0U7IrtFOz47RTs/+0U
7P/tFOz27RTscAAAAAAAAAAAAAAAADMpti0zKbbVMym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8z
Kbb/Mii3/y8mqv/tFOz07RTsRwAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsE+0U7MntFOz/7RTs/+0U7P/tFOy77RTsEAAAAAAAAAAA
Mym2AjMptmgzKbb1Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/ywjofggGXdMAAAA
AAAAAAAAAAAAAAAAAAAAAADtFOwI7RTslO0U7P/tFOz/7RTs/+0U7N/tFOwxAAAAAAAAAAAAAAAAMym2CzMptp8zKbb9Mym2/zMp
tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii1/jIotJcyKLcKAAAAAAAAAAAAAAAAAAAAAO0U7Ant
FOyd7RTs/+0U7P/tFOz/7RTs6+0U7D4AAAAAAAAAAAAAAAAAAAAAMym1MjMptdwzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/
Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii27jEot0gaFG4B7RTsAe0U7AHtFOwJ7RTsQ+0U7OHtFOz/7RTs/+0U7P/tFOzb7RTs
LQAAAAAAAAAAAAAAAAAAAAAwKK4FMCqrsjEpr/8yKbL/Mimz/zIps/8yKbP/Mimy/zIpsf8yKrD/Miqw/zIpsf8yKbL/Mym0/zIp
tv8yKLb+LSSm1e0U7JntFOyZ7RTsn+0U7LXtFOzm7RTs/u0U7P/tFOz/7RTs/u0U7LDtFOwLAAAAAAAAAAAAAAAAAAAAAC8qpwEv
KqetLyqn/y8qqf8vKqj/Lyqo/y8qqP8vKqj/Lyqo/y8qp/8vKqf/Lyqo/y8qqP8vKqj/MCqq/zAqrP8tKKT+7RTs/e0U7P3tFOz9
7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOzh7RTsSAAAAAAAAAAAAAAAAAAAAAAAAAAALimoBC8qp7EvKqf/Lyqo/y8qp/8vKqf/Lyqn
/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8spP8rKpf/ISF5/+0U7P/tFOz/7RTs/+0U7P3tFOz17RTs0O0U
7FDtFOwEAAAAAAAAAAAAAAAAAAAAAAAAAAAuKqcdLyqnyy8qp/8wKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8v
Kqf/Lyqn/y8qqP8vKqj/Lyqn/y4spf8uLaD/LCyb/ygoif8fH3D+7RTszu0U7F3tFOwW7RTsAwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAC8qpzIvKqffLyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqo/y8qqP8vKqf/Lyqn
/y8rpf8uLqH/Li6h/y4uof0uL6GaJCWEAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqnQC8qp+4vKqf/Lyqo/y8q
p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y8qp/8vKqf/Lyqn/y4to/8uLqH/Ly+h9jk6pWAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqc3Lyqn5C8qp/8vKqj/Lyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/
Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Liyk/y4uof8wMKHoPT6lGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAC4ppxgvKqfELyqn/y8qp/8wKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8q
p/8vKqf/Lyqn/y8qp/8vLKX/Li6h/y8vorAwMKILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqoAS8qp4Av
Kqf5Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8spP8uLqH5
Li6hWy4vogIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnGS8qpswvKqb/Lyqn/y8qqP8vKqf/Lyqn
/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Li2j/y4uoc8uLqIjAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaYCLyqmSS8qp98vKqf+Lyqo/y8qqP8vKqf/Lyqn/y8qpv8vKqb/Lyqn/y8qp/8v
Kqj/Lyqn/y8qp/8vKqf/Lyqn/y8rpv8uLaL4Li6hei4togIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAvKqcELyqnVC8qp9YvKqf+Lyqo/y8qp/8vKqf/Lyqm/y8qpv8vKqf/Lyqo/y8qqP8vKqf/Lyqn/y8qp/8vKqb/Li2j
/i4uob4uLaEVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqYDLyqnMC8q
p6AvKqfrLyqp+i8qqP8vKqf/Lyqn/y8qqP8vKqn/Lyqn/y8qp/8vKqf/Lyql/y4so/0uLaHOLi6hMy0togEAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqmCi8qpy0vKqiFMCqpti8qpvAvKqf8
Lyqp+S8qp/4vKqf+MSyn/jAtpvguLaPjLi2iqC4soy0uLaECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaUMLimiWC8ppGsvKqhMLyqnUC8qp1E0MKdQMzKkSy4u
oTUuLKILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8H4P//B+D//wfB//8Hwf//B4P//weD//+HB//
/hwf//4YP5+GGD+MABgPwAAeA8AAH4PgAB/B8AAfwfAAD8H4AA/B+AAAAfgAAAP4AAAH+AAAH/gAAB/4AAA/+AAAP/gAAD/4AAB/
/AAAf/4AAP//AAD//4AB///gA///////KAAAABgAAAAwAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ATtFOx17RTs8e0U7PntFOzd7RTsR+0U7AMAAAAA7RTsBO0U7E3tFOzf7RTs+e0U
7PLtFOyJ7RTsDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ATtFOxx7RTs8+0U7P/tFOzj7RTsS+0U7AMA
AAAA7RTsEO0U7JDtFOz57RTs/u0U7NftFOxG7RTsAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7APtFOxk
7RTs7e0U7P/tFOzj7RTsS+0U7APtFOwB7RTsNu0U7NTtFOz+7RTs9u0U7JLtFOwRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAO0U7ALtFOxW7RTs5u0U7P/tFOzk7RTsTe0U7APtFOwL7RTsg+0U7PPtFOz+7RTs0O0U7DntFOwCAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ALtFOxG7RTs3e0U7P/tFOzq7RTsWO0U7AbtFOwy7RTsx+0U7P3t
FOzz7RTsfe0U7AwAAAAAAAAAAC8qpwIvKqcFLyqnAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPUZ/wHtFOw27RTs1u0U7P/tFOzu
7RTsX+0U7BDtFOx57RTs8e0U7P3tFOzF7RTsMu0U7AIAAAAAAAAAAC8qpyQvKqdbLyqnLy8qpwQyKbUBMym1BTMpthMyKLYmMii2
LDIoticYEmc+7RTs0u0U7P/tFOzu7RTsYe0U7DXtFOzE7RTs/e0U7PbtFOyN7RTsFe0U7AIAAAAAAAAAAC8qp1QvKqfZLyqnsDEp
rTozKbU9Mym1bTMptZszKbbDMym2zjIotsMtJKew7RTs6e0U7P/tFOzx7RTsbe0U7HTtFOzs7RTs/O0U7PntFOzN7RTshe0U7Drt
FOwIAAAAADAqqigwKqyyMSmu8TIps8szKbXWMym28DMptvszKbb+Mym2/zMptv4yKLT8LCSk/h0Xcv/tFOz17RTsdu0U7FvtFOx6
7RTslO0U7M/tFOz17RTs9e0U7MXtFOxP7RTsBjEpsQUyKbRSMym12TMptvwzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii1
/y0kpf8ZFGf27RTsbu0U7w/tFOwJ7RTsEO0U7DftFOyw7RTs+u0U7PvtFOyz7RTsJAAAAAAzKbYQMym2hDMptvEzKbb/Mym2/zMp
tv8zKbb/Mym2/zMptv8zKbb/Mym2/zIotP8qIpz3Hhh2ce0U7AcAAAAAAAAAAO0U7AXtFOxh7RTs6u0U7P/tFOzh7RTsTQAAAAAz
KbYBMym2JzMptrMzKbb7Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8xKLP7MCavnTAnsRYAAAAAAAAAAO0U7ATtFOxZ
7RTs5u0U7P/tFOzv7RTsZwAAAAAAAAAAMym1BjIptFcyKbTmMym1/zMptf8zKbX/Mym1/zMptf8zKbT/Mym1/zMptf8yKLb/Mii2
4y0kqGPtFOwq7RTsK+0U7ELtFOyl7RTs9+0U7P/tFOzk7RTsUwAAAAAAAAAAAAAAADAqqjEwKqvUMCqt/zEqrv8xKq7/MSqt/zAq
rP8wKqz/MCqs/zEqrf8xKa//MSmw/CkjmeHtFOzI7RTsy+0U7NztFOz27RTs/u0U7PntFOyy7RTsJQAAAAAAAAAALiqnAS8qpzMv
KqfVLyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y0qn/8jIn/+7RTs/u0U7P/tFOz77RTs6u0U7LXtFOxE
7RTsBgAAAAAAAAAALiqnAy8qp0svKqfjLyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqo/y8qpv8uK6H/KyuY
/ycniP8fH3Pf7RTsbe0U7CDtFOwFAAAAAAAAAAAAAAAALyqnBS8qp2EvKqfvLyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q
p/8vKqj/Lyqo/y8qp/8vK6b/Li2j/y4uof0vMKC4MTGeIvUd/wEAAAAAAAAAAAAAAAAAAAAALyqnBS8qp14vKqfuLyqo/y8qp/8v
Kqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y8qp/8vKqf/Lyyl/y8uofgyMqKJOjulDAAAAAAAAAAAAAAAAAAAAAAAAAAA
LimnAi8qpz0vKqfWLyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vKqf/Lyul/y4uouQvL6JWNDSj
AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qpxUvKqeWLyqn9i8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8q
p/8vKqf/Lyyk/C4uorouLqEkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qpwIvKqY5Lyqnvi8qp/kvKqj/Lyqn/y8qp/8v
Kqb/Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vK6b/Li2j7C4uoXEuLqIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqYG
LyqnRC8qp7MvKqjuLyqo/S8qp/8vKqb/Lyqn/y8qqP8vKqf/Lyqn/y8qpv8vLKT2Li2iqC4uoSAuLqEBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnBS8qpykvKqdxLyqosi8qqNwvKqf3Lyqo+S8qqPsvK6f7MCum+C8spOYuLaKlLi2hNC4t
oQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4qpgEvKqcILyqoHy8qp0ovKaWHLyqngC8qp34x
LKd+MS+meC8to1kuLaIhLiyiBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/j4QD/48MA/+PDAP/jhwD/448A/+OPAP/jDwCcAwcA
gAODAMAD4QDAA/EA4AHxAPAB4QDwAAEA8AADAPAADwDwAA8A8AAPAPAAHwDwAB8A+AA/APwAPwD/AH8A/8//ACgAAAAQAAAAIAAA
AAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/2X/DO0U7E/tFOxa7RTsNQAAAAAAAAAA7RTsCu0U
7EztFOxa7RTsR/91/wUAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7BntFOzV7RTs/+0U7JUAAAAAAAAAAO0U7EXtFOzu7RTs/O0U7Ir/
//8CAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwQ7RTszO0U7P/tFOyZAAAAAJmZmQTtFOyh7RTs/+0U7NTtFOwjAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA7RTsCu0U7MDtFOz/7RTspgAAAADtFOw97RTs7e0U7PvtFOxmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AO0U7ATtFOyw7RTs/+0U7LDtFOwL7RTsp+0U7P/tFOy37RTsDgAAAAAAAAAAAAAAAAAAAAB0bdAEk47bAQAAAAD///0C7RTsq+0U
7P/tFOyu7RTsT+0U7PPtFOz/7RTsme0U7COTk5MCAAAAAAAAAAB5ctMLSkHEjE1ExlFqXuEqX1LfYDYtis/tFOz/7RTste0U7Fzt
FOyS7RTsve0U7PXtFOzh7RTsYAAAAAAAAAAA///rAVVK0H1NQNbpUEHc6E0/3P1MPd3/Sjvb/0c5zu5eUdZYAAAAAP93/wvtFOyP
7RTs/+0U7NvtFOwiAAAAAAAAAACGe+kRWUvfs0w93P9MPdz/TD3c/0w93f9LO9v/TD3W3GZa2zIAAAAA7RTsXu0U7P7tFOz37RTs
QwAAAAAAAAAAAAAAAGpe3zhNP9jrSTvY/0o72P9JO9f/STvX/0c41/9LPce57RTsau0U7M3tFOz/7RTs6+0U7DIAAAAAAAAAAAAA
AABaUsgZPjTC2Tovwv86L8H/OS7A/zkvwP87MMP/OC27/+0U7P/tFOz/7RTs7u0U7HntFOwFAAAAAAAAAAAAAAAAW1PJLD0zwOo3
Lb7/Ny29/zctvf83Lb3/Ny29/zguvv81K7v/MCar/zkxl4e+1AACAAAAAAAAAAAAAAAAAAAAAGJayyk+NcDoOC2+/zctvf83Lb3/
Ny29/zguvv84Lb7/Niy9/zcsuvRORMJEAAAAAAAAAAAAAAAAAAAAAAAAAACWkd0HSUDCnzkvv/83Lb7/Ny29/zctvf84Lr//Ny29
/zYsvP8/NbzCbWXLEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJayhxGPcKhPTPB8Dguvf44Lr7/OC6//zctvP87MbzrTUTBTgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcGnPCldOyUNKQcOYRDvCuElAw79DOr+mU0vDUaWh4AQAAAAAAAAAAAAAAAAA
AAAA//8AAPjjAAD4xwAA+M8AAPiPAAD4jwAAuIcAAMDjAADAcwAA4CMAAOAHAADgBwAA4A8AAOAPAADwHwAA/D8AAA==
ICON_DATA;
$icon = base64_decode( $icon );
$search = chr( 0xED ) . chr( 0x14 ) . chr( 0xEC );
$replace = chr( hexdec( substr( $_GET['c'], 4, 2 ) ) ) .
           chr( hexdec( substr( $_GET['c'], 2, 2 ) ) ) .
           chr( hexdec( substr( $_GET['c'], 0, 2 ) ) );
$icon = str_replace( $search, $replace, $icon );

// Override REDCap caching headers, to allow caching.
// Return a 304 status if icon unchanged from cached version.
header( 'Pragma: ' );
header( 'Expires: ' );
header( 'Cache-Control: max-age=2419200' );

$etag = substr( sha1( $icon ), 0, 12 );
if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) && $_SERVER['HTTP_IF_NONE_MATCH'] == $etag )
{
	header( 'HTTP/1.1 304 Not Modified' );
	exit;
}

// Output icon image.
header( 'Content-Type: image/x-icon' );
header( 'ETag: ' . $etag );
echo $icon;
