<?php

// Output the REDCap icon with the specified colour.


namespace Nottingham\REDCapUITweaker;


// Return 404 status if invalid colour specified.
if ( ! preg_match( '/^[0-9a-f]{6}$/', $_GET['c'] ) )
{
	header( 'HTTP/1.1 404 Not Found' );
	exit;
}

// Define icon image.
$icon = 'AAABAAQAMDAAAAEAIACoJQAARgAAACAgAAABACAAqBAAAO4lAAAYGAAAAQAgAIgJAACWNgAAEBAAAAEAIABoBAAA' .
        'HkAAACgAAAAwAAAAYAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzZ' .
        '7RTs9O0U7PTtFOz07RTs9O0U7PTtFOz07RTsUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsG+0U' .
        '7PHtFOz07RTs9O0U7PTtFOz07RTs9O0U7PTtFOx0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzz7RTs/+0U' .
        '7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsou0U7P/tFOz/' .
        '7RTs/+0U7P/tFOz/7RTs/+0U7PrtFOwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzV7RTs/+0U7P/tFOz/' .
        '7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwG7RTs9u0U7P/tFOz/7RTs/+0U' .
        '7P/tFOz/7RTs/+0U7IsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzQ7RTs/+0U7P/tFOz/7RTs/+0U' .
        '7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOxr7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/' .
        '7RTs8u0U7AYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOy77RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/' .
        '7RTsZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOzl7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTseQAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOyZ7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7EXtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOzp7RTsAgAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOyZ7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAO0U7NDtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOxVAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAADtFOxw7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsZQAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAA7RTsIe0U7P7tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAADtFOxL7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTskgAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        '7RTsxe0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAADtFOxL7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsowAAAAAAAAAAAAAAAAAAAADtFOwl7RTs/u0U' .
        '7P/tFOz/7RTs/+0U7P/tFOz/7RTszgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AADtFOw37RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAAAAAADtFOzB7RTs/+0U7P/tFOz/' .
        '7RTs/+0U7P/tFOz97RTsIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        '7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAO0U7B/tFOz97RTs/+0U7P/tFOz/7RTs/+0U' .
        '7P/tFOy4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTs/+0U' .
        '7P/tFOz/7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAAAAAAAO0U7LTtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7PztFOwU' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqmMC8qp+ovKqfeLyqmSAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTs/+0U7P/tFOz/' .
        '7RTs/+0U7P/tFOz/7RTsrQAAAAAAAAAA7RTsFu0U7PztFOz/7RTs/+0U7P/tFOz/7RTs/+0U7JkAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnxC8qp/8vKqf/Lyqn/i8qp10AAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAyKLYjMym2hDMpts0yKLftMii18zIotvMyKLfuMii3zjIot38wJ7cO7RTs++0U7P/tFOz/7RTs/+0U' .
        '7P/tFOz/7RTsrwAAAAAAAAAA7RTsre0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7OztFOyu7RTsOAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnoi8qp/8vKqf/Lyqn/y8qp/svKqYXAAAAAAAAAAAyKLZLMym2sTMp' .
        'te4yKbT/Mym2/zIps/8zKbb/Mym2/zMptv8yKLb/MSi0/zIot/8yKLb8IRp+/u0U7P/tFOz/7RTs/+0U7P/tFOz/' .
        '7RTsxwAAAADtFOwS7RTs/O0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7OrtFOxhAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAALymqEC8qqfYvKqf/Lyqn/y8qp/8wKa29Mym2vTMptvgzKbX/Mim0/zMptv8zKbb/' .
        'Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLX/Mii2/ywkoP/tFOz/7RTs/+0U7P/tFOz/7RTs3AAA' .
        'AADtFOyp7RTs/+0U7PztFOz87RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsxO0U7AQAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAADIps1kyKbL/Mimy/zIps/8zKbX/Mym1/zMptf8zKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii3/zEotP8vJqz/7RTs/+0U7P/tFOz/7RTs3QAAAADtFOwj' .
        '7RTsIwAAAAAAAAAA7RTsHe0U7F3tFOzD7RTs/u0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7M4AAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAzKbbBMym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/' .
        'Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLb/Liak/+0U7P/tFOz/7RTs3QAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAA7RTsKO0U7PHtFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOx/AAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAzKbYMMym29TMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8zKbb/Mym2/zMptv8zKbb/Mym2/zIot/8yKLf/Mii1/yghj//tFOz/7RTs3QAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAO0U7BvtFOz67RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz0AAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAMym2VzMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/' .
        'Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii3/zIotf8cFmf/7RTs3wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAADtFOyx7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsPgAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAADMptsAzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8zKbb/Mym2/zMptv8zKbb/Mii3/zIotf8xKLH/7RTs5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAADtFOxr7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTskwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMp' .
        'tgozKbb1Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/' .
        'Mym2/zMptv8zKbb/Mii3/zIot/8yKLX/MCep+TIotwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AADtFOxk7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyKbZV' .
        'Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8zKbb/Mym2/zIot/8yKLf/Mii2/zIot5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOx9' .
        '7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTsyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMym2vDMp' .
        'tv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/' .
        'Mym2/zMotv8yKLf/Mii2/zIotv0xJ7cmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ALtFOzh7RTs/+0U' .
        '7P/tFOz/7RTs/+0U7P/tFOz/7RTsoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCiuKjIps/8zKbb/' .
        'Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8yKLf/Mii3/zIotf8xKLfOAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwG7RTsS+0U7NztFOz/7RTs/+0U7P/tFOz/' .
        '7RTs/+0U7P/tFOz/7RTsXwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp/8wKqv/MSmv/zIp' .
        'sv8yKbP/Mimz/zIps/8yKbP/Mimz/zIpsf8xKbD/MSqu/zEqrf8xKq3/MSqt/zEpsP8xKbH/Mimz/zMptf8zKbb/' .
        'Mii3/zIot/8yKLX/7RTs3e0U7NztFOzc7RTs3O0U7OrtFOz77RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U' .
        '7P/tFOz57RTsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp/wvKqf/Lyqn/y8qqf8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8wKqn/MCmu/zAq' .
        'rv8xKbH/JR2N/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOx6' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp/4vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8rpv8uLqH/' .
        'Li2h/x8fbv/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7KEAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiipCi8qp/8vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8vK6b/Li2i/y4u' .
        'of8rK5f/ISFt/+0U7P/tFOz/7RTs/+0U7P/tFOz/7RTs/+0U7P/tFOz37RTsdgAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqnTS8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8qp/8vKqf/Lyqm/y4to/8uLqH/' .
        'Li6h/y0tnv8qKoj/Hx9r/+0U7P/tFOzq7RTswu0U7GLtFOwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAALiqniC8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqp/y8qp/8vKqf/Lyqn/y8qp/8uLKT/Li6h/y4u' .
        'of8uLqH/Li6h/y4uof8uLqHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAALyqnoi8qp/8vKqf/Lyqn/y8qqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Li2i/y4uof8uLqH/' .
        'Li6h/y4uof8uLqHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAALiqnzC8qp/8vKqf/Lyqn/y8qqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/MCqq/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyum/y4uof8uLqH/Li6h/y4u' .
        'of85OqadAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'Lyqnzy8qp/8vKqf/Lyqn/zAqqf8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqn/Lyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4tov8uLqH/Li6h/zAwof9OT6sz' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnoi8q' .
        'p/8vKqf/Lyqn/y8qqP8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqn/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4spP8uLqH/Li6h/zIyovYAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALimnYi8qp/8vKqf/' .
        'Lyqn/y8qp/8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q' .
        'p/8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8spf8uLqH/Li6h/zAworoAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALymqBC8qp/kvKqf/Lyqn/y8q' .
        'p/8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqn/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8spP8uLqH/Li6h/y4voksAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp6MvKqf/Lyqn/y8qp/8vKqj/' .
        'Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqn/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y4so/8uLqH/Li6h8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8rpwwvKqf3Lyql/y8qp/8vKqf/Lyqp/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y4uov8uLqH/Li6ijwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaZfLyqk/y8qp/8vKqf/Lyqn/zAqqf8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/zAqqv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyul/y4uof8uLqH6Li2jDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnki8qp/8vKqf/Lyqn/y8qqf8vKqj/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qpf8vKqb/Lyqn/y8qp/8vKqf/Lyqo/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/' .
        'Li2i/y4uof8uLqGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qp5QvKqf/Lyqn/y8qp/8wKqr/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qpP8vKqX/Lyqn/y8qp/8vKqf/Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vLKT/Li6h/y4u' .
        'oewtKaMGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqZlLyqn+S8qp/8vKqf/MCqq/y8qp/8vKqf/Lyqn/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqj/Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqm/y8rpf8uLqH/Li6h/S0toi4AAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALimnEC4qpq8vKqf7Lyqn/zAqqv8vKqj/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qqP8wKqr/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqX/Liui/y4uof8uLaH9Li2hUgAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqcMLyqneS8qp9gwKqr6Lyqp/y8qp/8vKqf/Lyqo/zAq' .
        'qv8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8uLKT/Li6h/y4touwuK6Q3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALymldC4po/8vKaT/Lyqp6C8qp/EvKqf9' .
        'Lyqn/y8qp/8wK6b/PDup+C4tousuLqHDLiyiZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0pnyouKZ8/AAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAD///gP/AcAAP//+A/4BwAA///4D/gHAAD///gP+A8AAP//+A/wHwAA///4D/Af' .
        'AAD///gP4D8AAP///A/gPwAA///8B8B/AAD///wHwH8AAP///AeA/wAA///8B4D/AAD///wHAf8AAM///AcB/wAA' .
        'h/gMBgD/AACDwAAGAD8AAMAAAAQADwAA4AAAB/AHAADgAAAH/AcAAPAAAAf+AwAA+AAAB/4DAAD4AAAH/wEAAPwA' .
        'AAf/AQAA/gAAA/8BAAD+AAAD/gEAAP8AAAH8AwAA/wAAAAADAAD/AAAAAAcAAP8AAAAABwAA/wAAAAAfAAD/AAAA' .
        'AH8AAP4AAAAA/wAA/gAAAAD/AAD+AAAAAP8AAP4AAAAB/wAA/gAAAAH/AAD/AAAAAf8AAP8AAAAD/wAA/wAAAAP/' .
        'AAD/gAAAA/8AAP/AAAAH/wAA/8AAAAf/AAD/4AAAD/8AAP/4AAAf/wAA//wAAD//AAD//4AAf/8AAP//8AH//wAA' .
        '////////AAAoAAAAIAAAAEAAAAABACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7BDtFOzZ7RTs9+0U7PftFOz37RTsxe0U7BwAAAAA' .
        'AAAAAAAAAAAAAAAA7RTsF+0U7L7tFOz37RTs9+0U7PftFOzr7RTsRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsEO0U7NntFOz/7RTs/+0U7P/tFOzO7RTsIQAAAAAAAAAA' .
        'AAAAAO0U7AHtFOxN7RTs8+0U7P/tFOz/7RTs/u0U7LbtFOwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwO7RTszO0U7P/tFOz/7RTs/+0U7M7tFOwhAAAAAAAAAAAAAAAA' .
        '7RTsCu0U7KbtFOz/7RTs/+0U7P/tFOzu7RTsSe0U7AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7AztFOy17RTs/+0U7P/tFOz/7RTszu0U7CEAAAAAAAAAAAAAAADtFOw0' .
        '7RTs7O0U7P/tFOz/7RTs/e0U7KvtFOwNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAA7RTsCu0U7KftFOz/7RTs/+0U7P/tFOzO7RTsIQAAAAAAAAAA7RTsBO0U7JftFOz8' .
        '7RTs/+0U7P/tFOzs7RTsOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAADtFOwG7RTshu0U7P/tFOz/7RTs/+0U7NjtFOwrAAAAAAAAAADtFOwx7RTs3e0U7P/tFOz/' .
        '7RTs/e0U7I3tFOwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAO0U7AXtFOx77RTs/+0U7P/tFOz/7RTs4u0U7DUAAAAA7RTsBu0U7IPtFOz97RTs/+0U7P/tFOze' .
        '7RTsMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAA7RTsAe0U7FztFOz+7RTs/+0U7P/tFOzk7RTsNwAAAADtFOwk7RTs4u0U7P/tFOz/7RTs++0U7IztFOwE' .
        'AAAAAAAAAAAAAAAAAAAAAC8qpgUvKqc3LyqnOC8qpggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyKLYBMii2ATIo' .
        'twEAAAAA7RTsUe0U7P7tFOz/7RTs/+0U7OTtFOw37RTsA+0U7IrtFOz77RTs/+0U7P/tFOza7RTsHwAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAALyqnLy8qp9cvKqflLyqnbC8qpwYAAAAAMym2BzMptREzKbY5Mym2gjIotqMyKLanMii3njIo' .
        't2rtFOxn7RTs/u0U7P/tFOz/7RTs5e0U7DjtFOwq7RTs1u0U7P/tFOz/7RTs/+0U7NvtFOxs7RTsG+0U7AUAAAAA' .
        'AAAAAAAAAAAvKqcmLyqn0S8qp/8vKqfqMCmtUjMptkwzKbWQMym12DMptfEzKbX6Mym2/jMptv4yKLb9Mii29y4l' .
        'qvMcFm//7RTs/+0U7P/tFOzu7RTsRe0U7HbtFOz77RTs/u0U7P7tFOz/7RTs/u0U7PftFOzg7RTsee0U7BUAAAAA' .
        'AAAAAC8pqgIwKq1kMSmv9DEpsP0yKbTrMym19jMptv4zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/zAn' .
        'r/8jHIX/7RTs/+0U7PTtFOxL7RTsTu0U7FftFOxW7RTsgu0U7NDtFOz57RTs/+0U7P/tFOz47RTspO0U7BAAAAAA' .
        'AAAAADMptQ4zKbamMym2/jMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/zEn' .
        'sf8fGXb/7RTs9O0U7EftFOwC7RTsAe0U7AHtFOwG7RTsF+0U7IrtFOz47RTs/+0U7P/tFOz27RTscAAAAAAAAAAA' .
        'AAAAADMpti0zKbbVMym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii3/y8m' .
        'qv/tFOz07RTsRwAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsE+0U7MntFOz/7RTs/+0U7P/tFOy77RTsEAAAAAAAAAAA' .
        'Mym2AjMptmgzKbb1Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mii2/ywj' .
        'ofggGXdMAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwI7RTslO0U7P/tFOz/7RTs/+0U7N/tFOwxAAAAAAAAAAAAAAAA' .
        'Mym2CzMptp8zKbb9Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii1/jIo' .
        'tJcyKLcKAAAAAAAAAAAAAAAAAAAAAO0U7AntFOyd7RTs/+0U7P/tFOz/7RTs6+0U7D4AAAAAAAAAAAAAAAAAAAAA' .
        'Mym1MjMptdwzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zMptv8yKLf/Mii27jEo' .
        't0gaFG4B7RTsAe0U7AHtFOwJ7RTsQ+0U7OHtFOz/7RTs/+0U7P/tFOzb7RTsLQAAAAAAAAAAAAAAAAAAAAAwKK4F' .
        'MCqrsjEpr/8yKbL/Mimz/zIps/8yKbP/Mimy/zIpsf8yKrD/Miqw/zIpsf8yKbL/Mym0/zIptv8yKLb+LSSm1e0U' .
        '7JntFOyZ7RTsn+0U7LXtFOzm7RTs/u0U7P/tFOz/7RTs/u0U7LDtFOwLAAAAAAAAAAAAAAAAAAAAAC8qpwEvKqet' .
        'Lyqn/y8qqf8vKqj/Lyqo/y8qqP8vKqj/Lyqo/y8qp/8vKqf/Lyqo/y8qqP8vKqj/MCqq/zAqrP8tKKT+7RTs/e0U' .
        '7P3tFOz97RTs/+0U7P/tFOz/7RTs/+0U7P/tFOzh7RTsSAAAAAAAAAAAAAAAAAAAAAAAAAAALimoBC8qp7EvKqf/' .
        'Lyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8spP8rKpf/ISF5/+0U' .
        '7P/tFOz/7RTs/+0U7P3tFOz17RTs0O0U7FDtFOwEAAAAAAAAAAAAAAAAAAAAAAAAAAAuKqcdLyqnyy8qp/8wKqn/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqj/Lyqn/y4spf8uLaD/LCyb/ygo' .
        'if8fH3D+7RTszu0U7F3tFOwW7RTsAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qpzIvKqffLyqn/y8qqP8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqo/y8qqP8vKqf/Lyqn/y8rpf8uLqH/Li6h/y4u' .
        'of0uL6GaJCWEAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqnQC8qp+4vKqf/Lyqo/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y8qp/8vKqf/Lyqn/y4to/8uLqH/Ly+h9jk6' .
        'pWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqc3Lyqn5C8qp/8vKqj/Lyqo/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/Liyk/y4uof8wMKHoPT6lGwAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4ppxgvKqfELyqn/y8qp/8wKqn/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqp/y8qp/8vKqf/Lyqn/y8qp/8vLKX/Li6h/y8vorAwMKILAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqoAS8qp4AvKqf5Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qqP8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8spP8uLqH5Li6hWy4vogIAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnGS8qpswvKqb/Lyqn/y8qqP8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqn/y8qp/8vKqf/MCqp/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Li2j/y4uoc8uLqIjAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaYCLyqmSS8qp98vKqf+Lyqo/y8qqP8vKqf/Lyqn/y8qpv8vKqb/' .
        'Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vKqf/Lyqn/y8rpv8uLaL4Li6hei4togIAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqcELyqnVC8qp9YvKqf+Lyqo/y8qp/8vKqf/Lyqm/y8qpv8vKqf/' .
        'Lyqo/y8qqP8vKqf/Lyqn/y8qp/8vKqb/Li2j/i4uob4uLaEVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKqYDLyqnMC8qp6AvKqfrLyqp+i8qqP8vKqf/Lyqn/y8qqP8vKqn/' .
        'Lyqn/y8qp/8vKqf/Lyql/y4so/0uLaHOLi6hMy0togEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiqmCi8qpy0vKqiFMCqpti8qpvAvKqf8Lyqp+S8qp/4vKqf+' .
        'MSyn/jAtpvguLaPjLi2iqC4soy0uLaECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKaUMLimiWC8ppGsvKqhMLyqnUC8qp1E0MKdQ' .
        'MzKkSy4uoTUuLKILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8H4P//B+D//wfB//8' .
        'Hwf//B4P//weD//+HB///hwf//4YP5+GGD+MABgPwAAeA8AAH4PgAB/B8AAfwfAAD8H4AA/B+AAAAfgAAAP4AAAH' .
        '+AAAH/gAAB/4AAA/+AAAP/gAAD/4AAB//AAAf/4AAP//AAD//4AB///gA///////KAAAABgAAAAwAAAAAQAgAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ATtFOx1' .
        '7RTs8e0U7PntFOzd7RTsR+0U7AMAAAAA7RTsBO0U7E3tFOzf7RTs+e0U7PLtFOyJ7RTsDwAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ATtFOxx7RTs8+0U7P/tFOzj7RTsS+0U7AMAAAAA7RTsEO0U7JDtFOz5' .
        '7RTs/u0U7NftFOxG7RTsAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7APtFOxk7RTs7e0U' .
        '7P/tFOzj7RTsS+0U7APtFOwB7RTsNu0U7NTtFOz+7RTs9u0U7JLtFOwRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAO0U7ALtFOxW7RTs5u0U7P/tFOzk7RTsTe0U7APtFOwL7RTsg+0U7PPtFOz+7RTs0O0U' .
        '7DntFOwCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ALtFOxG7RTs3e0U7P/tFOzq' .
        '7RTsWO0U7AbtFOwy7RTsx+0U7P3tFOzz7RTsfe0U7AwAAAAAAAAAAC8qpwIvKqcFLyqnAgAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAPUZ/wHtFOw27RTs1u0U7P/tFOzu7RTsX+0U7BDtFOx57RTs8e0U7P3tFOzF7RTsMu0U7AIAAAAA' .
        'AAAAAC8qpyQvKqdbLyqnLy8qpwQyKbUBMym1BTMpthMyKLYmMii2LDIoticYEmc+7RTs0u0U7P/tFOzu7RTsYe0U' .
        '7DXtFOzE7RTs/e0U7PbtFOyN7RTsFe0U7AIAAAAAAAAAAC8qp1QvKqfZLyqnsDEprTozKbU9Mym1bTMptZszKbbD' .
        'Mym2zjIotsMtJKew7RTs6e0U7P/tFOzx7RTsbe0U7HTtFOzs7RTs/O0U7PntFOzN7RTshe0U7DrtFOwIAAAAADAq' .
        'qigwKqyyMSmu8TIps8szKbXWMym28DMptvszKbb+Mym2/zMptv4yKLT8LCSk/h0Xcv/tFOz17RTsdu0U7FvtFOx6' .
        '7RTslO0U7M/tFOz17RTs9e0U7MXtFOxP7RTsBjEpsQUyKbRSMym12TMptvwzKbb/Mym2/zMptv8zKbb/Mym2/zMp' .
        'tv8zKbb/Mii1/y0kpf8ZFGf27RTsbu0U7w/tFOwJ7RTsEO0U7DftFOyw7RTs+u0U7PvtFOyz7RTsJAAAAAAzKbYQ' .
        'Mym2hDMptvEzKbb/Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/Mym2/zIotP8qIpz3Hhh2ce0U7AcAAAAAAAAAAO0U' .
        '7AXtFOxh7RTs6u0U7P/tFOzh7RTsTQAAAAAzKbYBMym2JzMptrMzKbb7Mym2/zMptv8zKbb/Mym2/zMptv8zKbb/' .
        'Mym2/zMptv8xKLP7MCavnTAnsRYAAAAAAAAAAO0U7ATtFOxZ7RTs5u0U7P/tFOzv7RTsZwAAAAAAAAAAMym1BjIp' .
        'tFcyKbTmMym1/zMptf8zKbX/Mym1/zMptf8zKbT/Mym1/zMptf8yKLb/Mii24y0kqGPtFOwq7RTsK+0U7ELtFOyl' .
        '7RTs9+0U7P/tFOzk7RTsUwAAAAAAAAAAAAAAADAqqjEwKqvUMCqt/zEqrv8xKq7/MSqt/zAqrP8wKqz/MCqs/zEq' .
        'rf8xKa//MSmw/CkjmeHtFOzI7RTsy+0U7NztFOz27RTs/u0U7PntFOyy7RTsJQAAAAAAAAAALiqnAS8qpzMvKqfV' .
        'Lyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y0qn/8jIn/+7RTs/u0U7P/tFOz77RTs6u0U' .
        '7LXtFOxE7RTsBgAAAAAAAAAALiqnAy8qp0svKqfjLyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqf/' .
        'Lyqo/y8qpv8uK6H/KyuY/ycniP8fH3Pf7RTsbe0U7CDtFOwFAAAAAAAAAAAAAAAALyqnBS8qp2EvKqfvLyqo/y8q' .
        'p/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y8qp/8vK6b/Li2j/y4uof0vMKC4MTGeIvUd/wEAAAAA' .
        'AAAAAAAAAAAAAAAALyqnBS8qp14vKqfuLyqo/y8qp/8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqo/y8q' .
        'p/8vKqf/Lyyl/y8uofgyMqKJOjulDAAAAAAAAAAAAAAAAAAAAAAAAAAALimnAi8qpz0vKqfWLyqn/y8qqP8vKqf/' .
        'Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vKqf/Lyul/y4uouQvL6JWNDSjAwAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAC8qpxUvKqeWLyqn9i8qqP8vKqf/Lyqn/y8qp/8vKqf/Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vKqf/' .
        'Lyyk/C4uorouLqEkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8qpwIvKqY5Lyqnvi8qp/kvKqj/Lyqn/y8q' .
        'p/8vKqb/Lyqn/y8qp/8vKqj/Lyqn/y8qp/8vK6b/Li2j7C4uoXEuLqIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAvKqYGLyqnRC8qp7MvKqjuLyqo/S8qp/8vKqb/Lyqn/y8qqP8vKqf/Lyqn/y8qpv8vLKT2Li2iqC4u' .
        'oSAuLqEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyqnBS8qpykvKqdxLyqosi8qqNwvKqf3' .
        'Lyqo+S8qqPsvK6f7MCum+C8spOYuLaKlLi2hNC4toQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAAAAAAC4qpgEvKqcILyqoHy8qp0ovKaWHLyqngC8qp34xLKd+MS+meC8to1kuLaIhLiyiBAAAAAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAP/j4QD/48MA/+PDAP/jhwD/448A/+OPAP/jDwCcAwcAgAODAMAD4QDAA/EA4AHxAPAB' .
        '4QDwAAEA8AADAPAADwDwAA8A8AAPAPAAHwDwAB8A+AA/APwAPwD/AH8A/8//ACgAAAAQAAAAIAAAAAEAIAAAAAAA' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/2X/DO0U7E/tFOxa7RTsNQAAAAAAAAAA7RTsCu0U' .
        '7EztFOxa7RTsR/91/wUAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7BntFOzV7RTs/+0U7JUAAAAAAAAAAO0U7EXtFOzu' .
        '7RTs/O0U7Ir///8CAAAAAAAAAAAAAAAAAAAAAAAAAADtFOwQ7RTszO0U7P/tFOyZAAAAAJmZmQTtFOyh7RTs/+0U' .
        '7NTtFOwjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7RTsCu0U7MDtFOz/7RTspgAAAADtFOw97RTs7e0U7PvtFOxm' .
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0U7ATtFOyw7RTs/+0U7LDtFOwL7RTsp+0U7P/tFOy37RTsDgAA' .
        'AAAAAAAAAAAAAAAAAAB0bdAEk47bAQAAAAD///0C7RTsq+0U7P/tFOyu7RTsT+0U7PPtFOz/7RTsme0U7COTk5MC' .
        'AAAAAAAAAAB5ctMLSkHEjE1ExlFqXuEqX1LfYDYtis/tFOz/7RTste0U7FztFOyS7RTsve0U7PXtFOzh7RTsYAAA' .
        'AAAAAAAA///rAVVK0H1NQNbpUEHc6E0/3P1MPd3/Sjvb/0c5zu5eUdZYAAAAAP93/wvtFOyP7RTs/+0U7NvtFOwi' .
        'AAAAAAAAAACGe+kRWUvfs0w93P9MPdz/TD3c/0w93f9LO9v/TD3W3GZa2zIAAAAA7RTsXu0U7P7tFOz37RTsQwAA' .
        'AAAAAAAAAAAAAGpe3zhNP9jrSTvY/0o72P9JO9f/STvX/0c41/9LPce57RTsau0U7M3tFOz/7RTs6+0U7DIAAAAA' .
        'AAAAAAAAAABaUsgZPjTC2Tovwv86L8H/OS7A/zkvwP87MMP/OC27/+0U7P/tFOz/7RTs7u0U7HntFOwFAAAAAAAA' .
        'AAAAAAAAW1PJLD0zwOo3Lb7/Ny29/zctvf83Lb3/Ny29/zguvv81K7v/MCar/zkxl4e+1AACAAAAAAAAAAAAAAAA' .
        'AAAAAGJayyk+NcDoOC2+/zctvf83Lb3/Ny29/zguvv84Lb7/Niy9/zcsuvRORMJEAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AACWkd0HSUDCnzkvv/83Lb7/Ny29/zctvf84Lr//Ny29/zYsvP8/NbzCbWXLEQAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAGJayhxGPcKhPTPB8Dguvf44Lr7/OC6//zctvP87MbzrTUTBTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' .
        'AAAAAAAAcGnPCldOyUNKQcOYRDvCuElAw79DOr+mU0vDUaWh4AQAAAAAAAAAAAAAAAAAAAAA//8AAPjjAAD4xwAA' .
        '+M8AAPiPAAD4jwAAuIcAAMDjAADAcwAA4CMAAOAHAADgBwAA4A8AAOAPAADwHwAA/D8AAA==';
$icon = base64_decode( $icon );
$search = chr( 0xED ) . chr( 0x14 ) . chr( 0xEC );
$replace = chr( hexdec( substr( $_GET['c'], 4, 2 ) ) ) .
           chr( hexdec( substr( $_GET['c'], 2, 2 ) ) ) .
           chr( hexdec( substr( $_GET['c'], 0, 2 ) ) );
$icon = str_replace( $search, $replace, $icon );

// Override REDCap caching headers, to allow caching.
// Return a 304 status if icon unchanged from cached version.
header( 'Pragma: ' );
header( 'Expires: ' );
header( 'Cache-Control: max-age=2419200' );

$etag = substr( sha1( $icon ), 0, 12 );
if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) && $_SERVER['HTTP_IF_NONE_MATCH'] == $etag )
{
	header( 'HTTP/1.1 304 Not Modified' );
	exit;
}

// Output icon image.
header( 'Content-Type: image/x-icon' );
header( 'ETag: ' . $etag );
echo $icon;
