# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_init(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.execute_script("if(window.location.hostname==\'127.0.0.1\'){sessionStorage.setItem(\'test-userdetails\',JSON.stringify({\"user1\":\"admin\",\"pass1\":\"abc123\",\"user2\":\"user\",\"pass2\":\"abc123\"}));document.body.setAttribute(\'data-setdetails\',1)}else{simpleDialog(\'<table><tr><td>Administrator username</td><td><input type=\"text\" name=\"test-user1\"></td></tr><tr><td>Administrator password</td><td><input type=\"password\" name=\"test-pass1\"></td></tr><tr><td>Standard user username</td><td><input type=\"text\" name=\"test-user2\"></td></tr><tr><td>Standard user password</td><td><input type=\"password\" name=\"test-pass2\"></td></tr></table><p>Standard user must not be currently assigned to any projects.</p>\',\'Enter user credentials\',null,null,function(){sessionStorage.setItem(\'test-userdetails\',JSON.stringify({\"user1\":$(\'[name=\"test-user1\"]\').val(),\"pass1\":$(\'[name=\"test-pass1\"]\').val(),\"user2\":$(\'[name=\"test-user2\"]\').val(),\"pass2\":$(\'[name=\"test-pass2\"]\').val()}));document.body.setAttribute(\'data-setdetails\',1)});$(\'[name=\"test-user1\"]\').val($(\'#username-reference\').text())}")
    WebDriverWait(self.driver, 600).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body[data-setdetails]")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) == 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "field-default-required")))
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal button.close").click()
    if self.driver.execute_script("return ($(\'[name=\"field-default-required\"]:checked\').length == 0)"):
      self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-disable-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "external-modules-disable-button-confirmed")))
      self.driver.find_element(By.ID, "external-modules-disable-button-confirmed").click()
      time.sleep(5)
      self.driver.execute_script("$(\'body\').attr(\'data-mustwait\',\'1\');window.location=window.location.href")
      time.sleep(0.5)
      while self.driver.execute_script("return ($(\'body\').attr(\'data-mustwait\') == \'1\')"):
        time.sleep(1)
      time.sleep(0.5)
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "external-modules-enable-modules-button")))
      self.driver.execute_script("$(\'.ui-widget-overlay.ui-front\').css(\'display\',\'none\')")
      self.driver.find_element(By.ID, "external-modules-enable-modules-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.enable-button")))
      self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.enable-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#external-modules-enable-modal button.enable-button")))
      self.driver.find_element(By.CSS_SELECTOR, "#external-modules-enable-modal button.enable-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".ui-dialog .close-button")))
      self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog .close-button").click()
    self.driver.find_element(By.LINK_TEXT, "New Project").click()
    self.driver.find_element(By.ID, "app_title").send_keys("REDCap UI Tweaker Test")
    dropdown = self.driver.find_element(By.ID, "purpose")
    dropdown.find_element(By.XPATH, "//option[. = 'Practice / Just for fun']").click()
    self.driver.find_element(By.ID, "project_template_radio1").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"copyof\"][value=\"5\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primaryrc").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    time.sleep(0.5)
    self.driver.find_element(By.ID, "setupEnableSurveysBtn").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[onclick*=\"Surveys/create_survey.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "surveySettingsSubmit")))
    time.sleep(1)
    self.driver.find_element(By.ID, "surveySettingsSubmit").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#external-modules-enabled tr[data-module=\"redcap_ui_tweaker\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]:not([href*=\"logout=1\"])").click()
    self.driver.find_element(By.ID, "new_rolename").send_keys("TestRole")
    self.driver.find_element(By.ID, "createRoleBtn").click()
    self.driver.execute_script("$(\'#editUserPopup input[type=\"checkbox\"]:not([disabled])\').prop(\'checked\',true)")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button[style*=\"bold\"]").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]:not([href*=\"logout=1\"])").click()
    self.driver.find_element(By.CSS_SELECTOR, ".userLinkInTable").click()
    self.driver.find_element(By.ID, "assignUserBtn2").click()
    time.sleep(0.5)
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'TestRole']").click()
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]:not([href*=\"logout=1\"])").click()
    self.driver.find_element(By.ID, "new_rolename").send_keys("TestRole2")
    self.driver.find_element(By.ID, "createRoleBtn").click()
    self.driver.execute_script("$(\'#editUserPopup input[type=\"checkbox\"]:not([disabled])\').prop(\'checked\',false)")
    self.driver.execute_script("$(\'#editUserPopup input[type=\"checkbox\"][name=\"record_create\"]\').prop(\'checked\',true)")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button[style*=\"bold\"]").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]:not([href*=\"logout=1\"])").click()
    self.vars["username"] = self.driver.execute_script("return JSON.parse(sessionStorage.getItem(\'test-userdetails\')).user2")
    self.driver.find_element(By.ID, "new_username_assign").send_keys(self.vars["username"])
    self.driver.find_element(By.ID, "assignUserBtn").click()
    time.sleep(3)
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'TestRole2']").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"notify_email_role\"]")
    if element.is_selected: element.click()
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    time.sleep(3)
  
