# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT26Projecthomepageredirect():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t26Projecthomepageredirect(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "project-home-redirect")))
    self.driver.find_element(By.NAME, "project-home-redirect").send_keys("DataEntry/record_status_dashboard.php?pid=*")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.XPATH, "//div[@id=\'home_setup_panel\']//a[contains(.,\'Home\')][contains(@href,\'index.php?pid=\')]").click()
    self.driver.execute_script("if (window.location.href.includes(\'record_status_dashboard\')) document.body.setAttribute(\'data-homeredirect\',1)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-homeredirect]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "project-home-redirect")))
    self.driver.execute_script("$(\'[name=\"project-home-redirect\"]\').val(\'\')")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
