# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT37Allusersautofillondev():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t37Allusersautofillondev(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"show-autofill-development\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',$(\'[name=\"show-autofill-development\"]\').prop(\'checked\'))")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"show-autofill-development\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ControlCenter/general_settings.php\"]").click()
    dropdown = self.driver.find_element(By.NAME, "is_development_server")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='0']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Surveys/invite_participants.php\"]").click()
    self.driver.execute_script("sessionStorage.setItem(\'test-surveylink\',$(\'#longurl\').val())")
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"MoveToProd()\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.ID, "keep_data").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Move to Production\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.execute_script("$(\'#footer\').remove()")
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    self.driver.execute_script("$(\'#footer\').remove();window.location.href=sessionStorage.getItem(\'test-surveylink\')")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")
    assert len(elements) == 0
    self.driver.execute_script("window.history.back()")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "rc-login-form")))
    self.driver.execute_script("$(\'#username\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).user2);$(\'#password\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).pass2)")
    self.driver.find_element(By.ID, "login_btn").click()
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.execute_script("window.location.href=sessionStorage.getItem(\'test-surveylink\')")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")
    assert len(elements) == 0
    self.driver.execute_script("window.history.back()")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"DataEntry/record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "button[onclick*=\"autoFill()\"]")
    assert len(elements) == 0
    self.driver.execute_script("window.dataEntryFormValuesChanged=false")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    self.driver.execute_script("$(\'#username\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).user1);$(\'#password\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).pass1)")
    self.driver.find_element(By.ID, "login_btn").click()
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/other_functionality.php\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"MoveToDev\"]").click()
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    for i in range(0, 2):
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.execute_script("$(\'#footer\').remove()")
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
      self.driver.execute_script("$(\'#footer\').remove();window.location.href=sessionStorage.getItem(\'test-surveylink\')")
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")))
      elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")
      assert len(elements) > 0
      self.driver.execute_script("window.history.back()")
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "rc-login-form")))
      self.driver.execute_script("$(\'#username\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).user2);$(\'#password\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).pass2)")
      self.driver.find_element(By.ID, "login_btn").click()
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
      self.driver.execute_script("window.location.href=sessionStorage.getItem(\'test-surveylink\')")
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")))
      elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"autoFill()\"]")
      assert len(elements) > 0
      self.driver.execute_script("window.history.back()")
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
      self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"DataEntry/record_status_dashboard.php\"]").click()
      self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "button[onclick*=\"autoFill()\"]")))
      elements = self.driver.find_elements(By.CSS_SELECTOR, "button[onclick*=\"autoFill()\"]")
      assert len(elements) > 0
      self.driver.execute_script("window.dataEntryFormValuesChanged=false")
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      self.driver.execute_script("$(\'#username\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).user1);$(\'#password\').val(JSON.parse(sessionStorage.getItem(\'test-userdetails\')).pass1)")
      self.driver.find_element(By.ID, "login_btn").click()
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
      self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]:not([href*=\"logout\"])").click()
      if self.driver.execute_script("return ($(\'button[onclick*=\"MoveToProd()\"]:visible\').length == 1)"):
        self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"MoveToProd()\"]").click()
        self.driver.execute_script("$(\'#south\').remove()")
        self.driver.find_element(By.ID, "keep_data").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Move to Production\')]").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
        self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ControlCenter/general_settings.php\"]").click()
        dropdown = self.driver.find_element(By.NAME, "is_development_server")
        dropdown.find_element(By.CSS_SELECTOR, "*[value='1']").click()
        self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/other_functionality.php\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"MoveToDev\"]").click()
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"show-autofill-development\"]")))
    self.driver.execute_script("$(\'[name=\"show-autofill-development\"]\').prop(\'checked\',sessionStorage.getItem(\'test-savedsetting\')==\'true\')")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
