# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT41BUTTONONLYactiontag():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_t41BUTTONONLYactiontag(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"buttononly\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify($(\'[name=\"buttononly\"]\').prop(\'checked\')))")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"buttononly\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Basic Demography Form").click()
    self.driver.find_element(By.CSS_SELECTOR, "[onclick*=\"openAddQuesForm(\'dob\'\"][data-field-action=\"edit-field\"]").click()
    time.sleep(1)
    self.driver.execute_script("$(\'#field_annotation\').val(\'@BUTTONONLY(\\\'My Button\\\')\')")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset .ui-button[style*=\"bold\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]")))
    elements = self.driver.find_elements(By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]")
    assert len(elements) > 0
    value = self.driver.find_element(By.NAME, "dob").get_attribute("value")
    assert value == ""
    self.driver.find_element(By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]").click()
    self.vars["today"] = self.driver.execute_script("return new Date().toISOString().substring(0,10)")
    value = self.driver.find_element(By.NAME, "dob").get_attribute("value")
    assert value == self.vars["today"]
    self.driver.execute_script("dataEntryFormValuesChanged=false")
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Basic Demography Form").click()
    self.driver.find_element(By.CSS_SELECTOR, "[onclick*=\"openAddQuesForm(\'dob\'\"][data-field-action=\"edit-field\"]").click()
    time.sleep(1)
    self.driver.execute_script("$(\'#field_annotation\').val(\'@BUTTONONLY(\\\'My Button\\\',\\\'record\\\')\')")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset .ui-button[style*=\"bold\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]")))
    elements = self.driver.find_elements(By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]")
    assert len(elements) > 0
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.XPATH, "//button[contains(@onclick,\'setToday\')][contains(text(),\'My Button\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    elements = self.driver.find_elements(By.NAME, "dob")
    assert len(elements) == 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"buttononly\"]")))
    self.driver.execute_script("$(\'[name=\"buttononly\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\')))")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)

