# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT27Customlogonameoptions():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t27Customlogonameoptions(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ControlCenter/edit_project.php\"]").click()
    dropdown = self.driver.find_element(By.NAME, "display_project_logo_institution")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='1']").click()
    self.driver.find_element(By.NAME, "institution").send_keys("Example Institution")
    self.driver.find_element(By.NAME, "site_org_type").send_keys("Example Org")
    self.driver.find_element(By.NAME, "headerlogo").send_keys("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD/gAAgfBVpAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWP4DwABAQEANl9ngAAAAABJRU5ErkJggg==")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"][value=\"Save Changes\"]").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"custom-logo-name-display\"][value=\"logo\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.execute_script("if ($(\'#subheader img[src*=\"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD/gAAgfBVpAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWP4DwABAQEANl9ngAAAAABJRU5ErkJggg\"]:visible\').length == 1 && $(\'#subheaderDiv1:visible\').length == 0) document.body.setAttribute(\'data-customlogoname\',1)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-customlogoname]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"custom-logo-name-display\"][value=\"name\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.execute_script("if ($(\'#subheader img[src*=\"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD/gAAgfBVpAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWP4DwABAQEANl9ngAAAAABJRU5ErkJggg\"]:visible\').length == 0 && $(\'#subheaderDiv1:visible\').length == 1) document.body.setAttribute(\'data-customlogoname\',1)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-customlogoname]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"custom-logo-name-display\"][value=\"\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.execute_script("if ($(\'#subheader img[src*=\"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD/gAAgfBVpAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWP4DwABAQEANl9ngAAAAABJRU5ErkJggg\"]:visible\').length == 1 && $(\'#subheaderDiv1:visible\').length == 1) document.body.setAttribute(\'data-customlogoname\',1)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-customlogoname]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ControlCenter/edit_project.php\"]").click()
    dropdown = self.driver.find_element(By.NAME, "display_project_logo_institution")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='0']").click()
    self.driver.execute_script("$(\'[name=\"institution\"]\').val(\'\')")
    self.driver.execute_script("$(\'[name=\"site_org_type\"]\').val(\'\')")
    self.driver.execute_script("$(\'[name=\"headerlogo\"]\').val(\'\')")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"][value=\"Save Changes\"]").click()
    time.sleep(1)
  
