# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT11Hidecontactadminlinks():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t11Hidecontactadminlinks(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"hide-contact-admin\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',$(\'[name=\"hide-contact-admin\"]:checked\').val())")
    self.driver.execute_script("$(\'[name=\"hide-contact-admin\"]\').first().prop(\'checked\',true)")
    for i in range(0, 4):
      self.vars["selectedoption"] = self.driver.execute_script("return $(\'[name=\\u0022hide-contact-admin\\u0022]:checked\').val()")
      self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
      time.sleep(2)
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
      self.driver.execute_script("if($(\'#menu-div .btn-contact-admin:visible\').length>0) document.body.setAttribute(\'data-link1\',1);if($(\'#help_panel .btn-contact-admin:visible\').length>0) document.body.setAttribute(\'data-link2\',1)")
      if self.driver.execute_script("return (arguments[0] != \'first\' && arguments[0] != \'all\')", self.vars["selectedoption"]):
        elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-link1]")
        assert len(elements) > 0
      else:
        elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-link1]")
        assert len(elements) == 0
      if self.driver.execute_script("return (arguments[0] != \'last\' && arguments[0] != \'all\')", self.vars["selectedoption"]):
        elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-link2]")
        assert len(elements) > 0
      else:
        elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-link2]")
        assert len(elements) == 0
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
      self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"hide-contact-admin\"]")))
      self.driver.execute_script("$(\'[name=\"hide-contact-admin\"]\').eq($(\'[name=\"hide-contact-admin\"]\').index($(\'[name=\"hide-contact-admin\"]:checked\'))+1).prop(\'checked\',true)")
    self.driver.execute_script("$(\'[name=\"hide-contact-admin\"][value=\"\'+sessionStorage.getItem(\'test-savedsetting\')+\'\"]\').prop(\'checked\',true)")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
