# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT33SFNsautomaticversionfields():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t33SFNsautomaticversionfields(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"static-form-names\"]\').prop(\'checked\'),$(\'[name=\"version-fields\"]\').prop(\'checked\'),$(\'[name=\"version-fields-default-annotation\"]\').val()]))")
    element = self.driver.find_element(By.NAME, "static-form-names")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "version-fields")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.NAME, "version-fields-default-annotation").send_keys("##version-field-annotation##")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
    self.driver.execute_script("showAddForm();addNewFormReveal(\'demographics\')")
    elements = self.driver.find_elements(By.ID, "new_form_var-demographics")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "new_form-demographics").send_keys("Form2")
    self.driver.find_element(By.ID, "new_form_var-demographics").send_keys("form2")
    self.driver.execute_script("addNewForm(\'demographics\')")
    time.sleep(1)
    self.driver.execute_script("window.location.reload()")
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Form2").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[data-field-action=\"edit-field\"][onclick*=\"form2_version\"]")
    assert len(elements) > 0
    self.driver.execute_script("$(\'div.popover-body\').css(\'display\',\'none\')")
    self.driver.find_element(By.CSS_SELECTOR, "a[data-field-action=\"edit-field\"][onclick*=\"form2_version\"]").click()
    self.driver.execute_script("if($(\'#field_annotation\').val().indexOf(\'##version-field-annotation##\')>-1)$(\'#field_annotation\').attr(\'data-testannotation\',\'1\')")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#field_annotation[data-testannotation]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//div[@aria-describedby=\'div_add_field\']//button[contains(.,\'Cancel\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".formActionDropdownTrigger[onclick*=\"form2\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"deleteForm(\"]").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Yes, delete it\')]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    self.driver.execute_script("$(\'[name=\"static-form-names\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]);$(\'[name=\"version-fields\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1]);$(\'[name=\"version-fields-default-annotation\"]\').val(JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[2])")
    time.sleep(0.2)
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
