# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT32Staticformnames():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t32Staticformnames(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    if self.driver.execute_script("return (window.redcap_version.split(\'.\')[0] < 15 || ( window.redcap_version.split(\'.\')[0] == 15 && window.redcap_version.split(\'.\')[1] < 1 ))"):
      elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
      assert len(elements) > 0
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
      self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
      self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',$(\'[name=\"static-form-names\"]\').prop(\'checked\'))")
      element = self.driver.find_element(By.NAME, "static-form-names")
      if element.is_selected() != True: element.click()
      self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
      time.sleep(2)
      self.driver.find_element(By.LINK_TEXT, "My Projects").click()
      self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
      self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
      self.driver.execute_script("showAddForm();addNewFormReveal(\'demographics\')")
      elements = self.driver.find_elements(By.ID, "new_form_var-demographics")
      assert len(elements) > 0
      self.driver.find_element(By.CSS_SELECTOR, ".formActionDropdownTrigger").click()
      self.driver.execute_script("setupRenameForm($(\'#ActionCurrentForm\').val())")
      self.driver.find_element(By.ID, "form_menu_description_input-demographics").send_keys("Demography")
      self.driver.find_element(By.ID, "form_menu_save_btn-demographics").click()
      self.driver.find_element(By.CSS_SELECTOR, ".close-button.ui-button").click()
      time.sleep(2)
      elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"page=demographics\"]")
      assert len(elements) > 0
      self.driver.find_element(By.CSS_SELECTOR, ".formActionDropdownTrigger").click()
      self.driver.execute_script("setupRenameForm($(\'#ActionCurrentForm\').val())")
      self.driver.execute_script("$(\'#form_menu_description_input-demographics\').val(\'Basic Demography Form\')")
      self.driver.find_element(By.ID, "form_menu_save_btn-demographics").click()
      self.driver.find_element(By.CSS_SELECTOR, ".close-button.ui-button").click()
      time.sleep(2)
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
      self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
      self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
      WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
      self.driver.execute_script("$(\'[name=\"static-form-names\"]\').prop(\'checked\',sessionStorage.getItem(\'test-savedsetting\')==\'true\')")
      time.sleep(0.2)
      self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
      time.sleep(2)
  
