# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT13Submitoptions():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t13Submitoptions(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"submit-option-tweak\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"submit-option-tweak\"]:checked\').val(),$(\'[name=\"submit-option-define\"]\').val(),$(\'[name=\"submit-option-custom\"]\').prop(\'checked\')]))")
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option-tweak\"][value=\"2\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option-define\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option-define\"]").send_keys("continue,record")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option-custom\"]")
    if element.is_selected: element.click()
    self.driver.execute_script("$(\'[name=\"submit-option-custom\"]\').prop(\'checked\',false)")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Basic Demography Form").click()
    self.driver.execute_script("openAddQuesForm(\'comments\',\'textarea\',0,\'0\')")
    time.sleep(1)
    self.driver.execute_script("$(\'#field_annotation\').val(\'@SAVEOPTIONS=\\\'continue,exitrecord\\\'\')")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset .ui-button[style*=\"bold\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    self.driver.execute_script("$(function(){setTimeout(function(){if ([...new Set($(\'[id^=\"submit-btn-\"]:not([id=\"submit-btn-dropdown\"])\').map(function(){return this.id}).get())].join(\';\') == \'submit-btn-savecontinue;submit-btn-saverecord\') document.body.setAttribute(\'data-submitoptions\',1)},2000)})")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body[data-submitoptions]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-submitoptions]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"submit-option-tweak\"]")))
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option-custom\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"submit-option\"]").send_keys("record,exitrecord")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    self.driver.execute_script("$(function(){if ([...new Set($(\'[id^=\"submit-btn-\"]:not([id=\"submit-btn-dropdown\"])\').map(function(){return this.id}).get())].join(\';\') == \'submit-btn-savecontinue;submit-btn-saveexitrecord\') document.body.setAttribute(\'data-submitoptions\',1)})")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body[data-submitoptions]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-submitoptions]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Basic Demography Form").click()
    self.driver.execute_script("openAddQuesForm(\'comments\',\'textarea\',0,\'0\')")
    time.sleep(1)
    self.driver.execute_script("$(\'#field_annotation\').val(\'\')")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset .ui-button[style*=\"bold\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"DataEntry/record_home.php\"]").click()
    self.driver.execute_script("$(function(){if ([...new Set($(\'[id^=\"submit-btn-\"]:not([id=\"submit-btn-dropdown\"])\').map(function(){return this.id}).get())].join(\';\') == \'submit-btn-saverecord;submit-btn-saveexitrecord\') document.body.setAttribute(\'data-submitoptions\',1)})")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body[data-submitoptions]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-submitoptions]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] .external-modules-configure-button").click()
    self.driver.execute_script("$(\'[name=\"submit-option\"]\').val(\'\')")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"submit-option-tweak\"]")))
    self.driver.execute_script("$(\'[name=\"submit-option-define\"]\').val(JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1]);$(\'[name=\"submit-option-tweak\"][value=\"\'+JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]+\'\"]\').click();$(\'[name=\"submit-option-custom\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[2])")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
