# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT18Projectsimplifiedviews():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t18Projectsimplifiedviews(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"alerts-simplified-view\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"alerts-simplified-view\"]\').prop(\'checked\'),$(\'[name=\"codebook-simplified-view\"]\').prop(\'checked\'),$(\'[name=\"extmod-simplified-view\"]:checked\').val(),$(\'[name=\"quality-rules-simplified-view\"]\').prop(\'checked\'),$(\'[name=\"instrument-simplified-view\"]\').prop(\'checked\'),$(\'[name=\"reports-simplified-view\"]\').prop(\'checked\'),$(\'[name=\"user-rights-simplified-view\"]\').prop(\'checked\')]))")
    element = self.driver.find_element(By.NAME, "alerts-simplified-view")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "codebook-simplified-view")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"extmod-simplified-view\"][value=\"A\"]")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "quality-rules-simplified-view")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "instrument-simplified-view")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "reports-simplified-view")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "user-rights-simplified-view")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"AlertsController:setup\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"data_dictionary_codebook.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"ExternalModules/manager/project.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"DataQuality/index.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.ID, "setupLongiBtn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Define My Events\')]").click()
    self.driver.find_element(By.ID, "descrip").send_keys("Event 2")
    self.driver.find_element(By.ID, "addbutton").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/designate_forms.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Define My Events\')]").click()
    self.driver.find_element(By.XPATH, "(//a[contains(@onclick, \'delVisit\')])[last()]").click()
    self.driver.switch_to.alert.accept()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.ID, "setupLongiBtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"DataExport/index.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]").click()
    time.sleep(1)
    elements = self.driver.find_elements(By.ID, "simplifiedView")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "simplifiedView").click()
    elements = self.driver.find_elements(By.ID, "selectTable")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"alerts-simplified-view\"]")))
    self.driver.execute_script("$(\'[name=\"alerts-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]);$(\'[name=\"codebook-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1]);$(\'[name=\"extmod-simplified-view\"][value=\"\'+JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[2]+\'\"\').prop(\'checked\',true);$(\'[name=\"quality-rules-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[3]);$(\'[name=\"instrument-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[4]);$(\'[name=\"reports-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[5]);$(\'[name=\"user-rights-simplified-view\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[6])")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
