# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT35SFNspreserveformlabels():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t35SFNspreserveformlabels(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"static-form-names\"]\').prop(\'checked\'),$(\'[name=\"preserve-form-labels\"]\').prop(\'checked\')]))")
    element = self.driver.find_element(By.NAME, "static-form-names")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.NAME, "preserve-form-labels")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
    self.driver.execute_script("$.get(window.location.href.replace(\'online_designer\',\'zip_instrument_download\')+\'&page=demographics\')")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    element = self.driver.find_element(By.NAME, "preserve-form-labels")
    if element.is_selected: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Basic Demography Form").click()
    time.sleep(2)
    self.driver.execute_script("$(\'div.popover-body\').css(\'display\',\'none\')")
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"openAddQuesForm\"]").click()
    self.driver.execute_script("if($(\'#field_annotation\').val().includes(\'##UITweaker-FormName:Basic Demography Form\') ) $(\'body\').attr(\'data-savedlabel\',\'1\')")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-savedlabel]")
    assert len(elements) > 0
    self.driver.execute_script("$(\'#field_annotation\').val($(\'#field_annotation\').val().replace(\'Basic Demography Form\',\'Demography Form Basic\'))")
    self.driver.find_element(By.XPATH, "//div[@aria-describedby=\'div_add_field\']//button[contains(.,\'Save\')]").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    element = self.driver.find_element(By.NAME, "preserve-form-labels")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "REDCap UI Tweaker Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]").click()
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Demography Form Basic\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Demography Form Basic").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"][href*=\"page=demographics\"]")
    assert len(elements) > 0
    self.driver.execute_script("$(\'div.popover-body\').css(\'display\',\'none\')")
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"openAddQuesForm\"]").click()
    self.driver.execute_script("$(\'#field_annotation\').val(\'##UITweaker-FormName:Basic Demography Form\')")
    self.driver.find_element(By.XPATH, "//div[@aria-describedby=\'div_add_field\']//button[contains(.,\'Save\')]").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"Design/online_designer.php\"]:not([href*=\"logout=1\"])").click()
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Basic Demography Form\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"][href*=\"page=demographics\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.NAME, "static-form-names")))
    self.driver.execute_script("$(\'[name=\"static-form-names\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]);$(\'[name=\"preserve-form-labels\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1])")
    time.sleep(0.2)
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
