# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT25VersionlessURLs():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t25VersionlessURLs(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"versionless-url\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"versionless-url\"]:checked\').val(),$(\'[name=\"versionless-url-regex\"]\').val()]))")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"versionless-url\"][value=\"M\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"versionless-url-regex\"]").send_keys("^ControlCenter/general_settings\\.php")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ControlCenter/general_settings.php\"]").click()
    self.driver.execute_script("if (!window.location.href.includes(\'/redcap_v\')) document.body.setAttribute(\'data-versionless\',1)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body[data-versionless]")
    assert len(elements) > 0
    self.driver.execute_script("window.history.back()")
    time.sleep(2)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"versionless-url\"]")))
    self.driver.execute_script("$(\'[name=\"versionless-url\"][value=\"\'+JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]+\'\"]\').prop(\'checked\',true);$(\'[name=\"versionless-url-regex\"]\').val(JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1])")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
