# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT40Theme():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t40Theme(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'REDCap UI Tweaker Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ControlCenter/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href$=\"ExternalModules/manager/control_center.php\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"theme-banner\"]")))
    self.driver.execute_script("sessionStorage.setItem(\'test-savedsetting\',JSON.stringify([$(\'[name=\"theme-banner\"]\').prop(\'checked\'),$(\'[name=\"theme-banner-text\"]\').val(),$(\'[name=\"theme-edge\"]\').prop(\'checked\'),$(\'[name=\"theme-icon\"]\').prop(\'checked\'),$(\'[name=\"theme-hue\"]:checked\').val()]))")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-banner\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-banner-text\"]").send_keys("Hello!")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-hue\"][value=\"blue\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    elements = self.driver.find_elements(By.XPATH, "//div[contains(@style,\'--page-top\')][contains(@style,\'1000000\')][contains(@style,\'background-color: rgb(0, 100, 255)\')][contains(@style,\' color: rgb(255, 255, 255)\')][contains(text(),\'Hello!\')]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"theme-banner\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-banner-text\"]").send_keys("World!")
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-hue\"][value=\"white\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    elements = self.driver.find_elements(By.XPATH, "//div[contains(@style,\'--page-top\')][contains(@style,\'1000000\')][contains(@style,\'background-color: rgb(255, 255, 255)\')][contains(@style,\' color: rgb(0, 0, 0)\')][contains(text(),\'World!\')]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"theme-banner\"]")))
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-hue\"][value=\"blue\"]")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-edge\"]")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.CSS_SELECTOR, "[name=\"theme-icon\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "[style*=\"999999\"][style*=\"4px solid rgb(0, 100, 255)\"]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "link[rel=\"shortcut icon\"][href*=\"page=redcap_icon\"][href*=\"c=0064ff\"]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"redcap_ui_tweaker\"] button.external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[name=\"theme-banner\"]")))
    self.driver.execute_script("$(\'[name=\"theme-banner\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[0]);$(\'[name=\"theme-banner-text\"]\').val(JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[1]);$(\'[name=\"theme-edge\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[2]);$(\'[name=\"theme-icon\"]\').prop(\'checked\',JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[3]);$(\'[name=\"theme-hue\"][value=\"\' + JSON.parse(sessionStorage.getItem(\'test-savedsetting\'))[4] + \'\"]\').prop(\'checked\',true)")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal .modal-footer .save").click()
    time.sleep(2)
  
